name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ministryofjustice/tech-docs-github-pages-publisher:v6.2.0
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Compile Markdown to HTML and create artifact
        run: |
          /usr/local/bin/package
      - name: Upload artifact to be published
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: github-pages
          path: artifact.tar
          retention-days: 1

  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Download a Build Artifact from build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: github-pages
          path: github-pages
      - name: Unpack files
        run: |
          cd github-pages
          tar -xvf artifact.tar
      - name: Generate slug
        id: generate_slug
        run: echo "##[set-output name=slug;]$(echo ${GITHUB_HEAD_REF#refs/heads/} | sed -r 's/[~\^]+//g' | sed -r 's/[^a-zA-Z0-9]+/-/g' | sed -r 's/^-+\|-+$//g' | tr A-Z a-z)"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f
        with:
          branch: gh-pages
          folder: github-pages
          target-folder: pr/${{ steps.generate_slug.outputs.slug }}
      - name: Publish env
        uses: marocchino/sticky-pull-request-comment@70d2764d1a7d5d9560b100cbea0077fc8f633987
        with:
          header: Preview environment
          message: |
            ## Preview environment
            https://user-guide.staff-identity.service.justice.gov.uk/pr/${{ steps.generate_slug.outputs.slug }}/index.html
