name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build:
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ministryofjustice/tech-docs-github-pages-publisher:v6.2.0
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Compile Markdown to HTML and create artifact
        run: |
          /usr/local/bin/package
      - name: Upload artifact to be published
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: github-pages
          path: artifact.tar
          retention-days: 1

  upload-preview-to-app-service:
    needs: build
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/upload-preview-to-app-service.yml
    with:
      artifact_name: github-pages
      deployment_action: deploy
      preview_subpath: pr/${{ github.event.pull_request.number }}
    secrets:
      AZURE_APP_SERVICE_NAME: ${{ secrets.AZURE_APP_SERVICE_NAME }}
      AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  publish-app-service-preview-url:
    needs: upload-preview-to-app-service
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Publish App Service preview URL
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: App Service preview environment
          message: |
            ## App Service preview environment
            https://user-guide.staff-identity.service.justice.gov.uk/pr/${{ github.event.pull_request.number }}/index.html
