name: Test

on:
  pull_request:
    branches:
      - main

# GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:v3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile Markdown to HTML and create artifact
        run: |
          /scripts/deploy.sh
